name: 'fbw-actions-qa-labels'
description: 'A GitHub Action to help with PR QA Comments and add/remove labels accordingly to the results'
author: 'flybywiresim'
icon: 'git-pull-request'
color: 'purple'
inputs:
  repo-owner: 
    description: 'The owner of the repo to run the action on'
    required: true
  repo-name:
    description: 'The name of the repo to run the action on'
    required: true
  pr-number:
    description: 'The PR number to run the action on'
    required: true
  github-token:
    description: 'GitHub access token'
    required: true
  label-pass:
    description: 'The label to add to the PR if the QA comment passes (optional)'
  label-fail:
    description: 'The label to add to the PR if the QA comment fails (optional)'
  label-rtt:
    description: 'The label to add to the PR if the QA comment is ready for testing (optional)'
  ready-for-review-label:
    description: 'The label to add to the PR if the QA comment passes (optional)'
  fail-action-if-no-qacomment:
    description: 'If true, the action will fail if there is no QA comment found when the action is run (optional)'
  fail-action-if-qa-failed:
    description: 'If true, the action will fail if the QA testing results is marked as Not Passed (optional)'
runs:
  using: 'node16'
  main: 'dist/index.mjs'
